fix magiskDb file does not exist
android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/adb/magisk.db' with flags 0x1: File /data/adb/magisk.db doesn't exist